#!/bin/bash

set -x
AUTOCONF_ARCHIVE=/usr/share/aclocal

# autotools invocations are hard to get right.

aclocal -I m4 -I libltdl -I $AUTOCONF_ARCHIVE -I /usr/share/aclocal
autoconf
automake

set +x
echo "To build phc, run \"./configure\" followed by \"make\""
