#!/bin/bash

#test/subjects/benchmarks/php-benchmarks/richards.php										\
#test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_j4p5.php				\
BENCHES="\
test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_crypto.php				\
test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_deltablue.php			\
test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_gaussjordan.php		\
test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_raytrace.php			\
test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_whirl.php				\
test/subjects/benchmarks/zend/bench_less_recursive.php									\
"

set -x

for i in $BENCHES;
do
	rm test_benches_output
	date >> test_benches_output 2>&1
	svn update >> test_benches_output 2>&1
	make >> test_benches_output 2>&1
	echo $i >> test_benches_output 2>&1
	time src/phc --include -O2 --stats $i >> test_benches_output 2>&1
	mail -t paul.biggar@gmail.com -s "benchmark test" < test_benches_output
done
