/* 
 * phc -- the open source PHP compiler 
 * See doc/license/README.license for licensing information
 *
 * Remove concatenations to empty strings (which are generated by the parser)
 */

#ifndef PHC_REMOVE_CONCAT_NULL
#define PHC_REMOVE_CONCAT_NULL

#include "AST_transform.h"

class Remove_concat_null : public AST::Transform, virtual public GC_obj
{
public:
	AST::Expr* post_bin_op(AST::Bin_op* in);
};

#endif // PHC_REMOVE_CONCAT_NULL
