#!/bin/bash

# Runs out the clock
#test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_crypto.php
#test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_deltablue.php
#test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_gaussjordan.php
#test/subjects/benchmarks/php-benchmarks/richards.php
#test/subjects/benchmarks/shootout/binarytrees.php
#test/subjects/benchmarks/shootout/nbody.php
#test/subjects/benchmarks/zend/bench_less_recursive.php

# Runs out of memory (on 4G)

# Beyond hope
#test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_j4p5.php

# Recursion
#test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_ackermann.php

# Poor benchmark
#test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_pcre.php

# Works
#test/subjects/benchmarks/shootout/fannkuch.php												\
#test/subjects/benchmarks/zend/individual/ary2.php											\
#test/subjects/benchmarks/zend/individual/ary3.php											\
#test/subjects/benchmarks/zend/individual/ary.php											\
#test/subjects/benchmarks/zend/individual/hash1.php											\
#test/subjects/benchmarks/zend/individual/hash2.php											\
#test/subjects/benchmarks/zend/individual/heapsort.php										\
#test/subjects/benchmarks/zend/individual/mandel2.php										\
#test/subjects/benchmarks/zend/individual/mandel.php										\
#test/subjects/benchmarks/zend/individual/matrix.php										\
#test/subjects/benchmarks/zend/individual/nestedloop.php									\
#test/subjects/benchmarks/zend/individual/sieve.php											\
#test/subjects/benchmarks/zend/individual/simplecall.php									\
#test/subjects/benchmarks/zend/individual/simple.php										\
#test/subjects/benchmarks/zend/individual/simpleucall.php									\
#test/subjects/benchmarks/zend/individual/simpleudcall.php								\
#test/subjects/benchmarks/zend/individual/strcat.php										\




BENCHES="\
test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_raytrace.php			\
test/subjects/benchmarks/php-benchmarks/benchcli/tests/test_whirl.php				\
test/subjects/benchmarks/RUBBoS/PHP/AcceptStory.php										\
test/subjects/benchmarks/RUBBoS/PHP/Author.php												\
test/subjects/benchmarks/RUBBoS/PHP/BrowseCategories.php									\
test/subjects/benchmarks/RUBBoS/PHP/BrowseStoriesByCategory.php						\
test/subjects/benchmarks/RUBBoS/PHP/ModerateComment.php									\
test/subjects/benchmarks/RUBBoS/PHP/OlderStories.php										\
test/subjects/benchmarks/RUBBoS/PHP/PHPprinter.php											\
test/subjects/benchmarks/RUBBoS/PHP/PostComment.php										\
test/subjects/benchmarks/RUBBoS/PHP/RegisterUser.php										\
test/subjects/benchmarks/RUBBoS/PHP/RejectStory.php										\
test/subjects/benchmarks/RUBBoS/PHP/ReviewStories.php										\
test/subjects/benchmarks/RUBBoS/PHP/Search.php												\
test/subjects/benchmarks/RUBBoS/PHP/StoreComment.php										\
test/subjects/benchmarks/RUBBoS/PHP/StoreModeratorLog.php								\
test/subjects/benchmarks/RUBBoS/PHP/StoreStory.php											\
test/subjects/benchmarks/RUBBoS/PHP/StoriesOfTheDay.php									\
test/subjects/benchmarks/RUBBoS/PHP/SubmitStory.php										\
test/subjects/benchmarks/RUBBoS/PHP/ViewComment.php										\
test/subjects/benchmarks/RUBBoS/PHP/ViewStory.php											\
test/subjects/benchmarks/shootout/fasta.php-2.php											\
test/subjects/benchmarks/shootout/knucleotide.php											\
test/subjects/benchmarks/shootout/pidigits.php												\
"

set -x
ulimit -t 1800 # 30 mins
ulimit -m 20000000 # 2G-ish

#!/bin/bash

SAVE_FILE="test_benches_output"

while true;
do
	for i in $BENCHES;
	do
		dirname=`dirname $i`

		rm -f $SAVE_FILE
		svn update
		make 2>&1 | tee -a $SAVE_FILE
		echo $i 2>&1 | tee -a $SAVE_FILE
		/usr/bin/time src/phc				\
			--include -O2 --stats -c		\
			-d include_path=$dirname $i	\
			2>&1 | tee -a $SAVE_FILE

		mail -t paul.biggar@gmail.com -s "benchmark test" < $SAVE_FILE
	done
done
